CREATE TABLE walmart_sales (
    store INTEGER,
    dept INTEGER,
    product VARCHAR(100),
    order_date DATE,
    weekly_sales DECIMAL(14, 2),
    revenue DECIMAL(14, 2),
    quantity INTEGER,
    unit_price DECIMAL(10, 2),
    discount DECIMAL(6, 4),
    holiday_flag INTEGER,
    temperature DECIMAL(8, 2),
    fuel_price DECIMAL(8, 3),
    cpi DECIMAL(10, 3),
    unemployment DECIMAL(8, 3),
    store_type VARCHAR(10),
    store_size INTEGER,
    region VARCHAR(50),
    category VARCHAR(100),
    profit DECIMAL(14, 2),
    profit_margin DECIMAL(8, 4),
    customer_segment VARCHAR(50),
    sales_year INTEGER,
    sales_month VARCHAR(7),
    sales_quarter VARCHAR(7),
    sales_week INTEGER
);
